#!/usr/bin/env bash
set -e

# Defaults
ReqId=""
TaskId=""
RepoRoot="$(pwd)"

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -ReqId) ReqId="$2"; shift ;;
        -TaskId) TaskId="$2"; shift ;;
        -RepoRoot) RepoRoot="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

if [ -z "$ReqId" ]; then
    echo "Error: -ReqId is required."
    exit 1
fi

forgeDir="$RepoRoot/.forge"
outputFile="$forgeDir/.active-context.md"

# Helpers
Normalize-Id() {
    local raw="$1"
    local prefix="$2"
    local num=$(echo "$raw" | sed 's/[^0-9]//g')
    if [ -z "$num" ]; then
        echo "$raw"
    else
        printf "%s-%03d" "$prefix" "$num"
    fi
}

Get-FrontmatterValue() {
    local filePath="$1"
    local key="$2"
    awk -v k="$key" '
        /^---$/ { if(in_fm) exit; else in_fm=1; next }
        in_fm && $0 ~ "^" k ":" {
            sub("^" k ":[[:space:]]*", "")
            gsub(/^["\047]|["\047]$/, "")
            print
            exit
        }
    ' "$filePath"
}

Get-SectionContent() {
    local filePath="$1"
    local heading="$2"
    awk -v h="^##[[:space:]]+$heading" '
        $0 ~ h { capture=1; next }
        capture && /^##[[:space:]]+/ { exit }
        capture { print }
    ' "$filePath" | sed -e '/^[[:space:]]*$/!b' -e '/./!d'
}

normalizedReq=$(Normalize-Id "$ReqId" "REQ")
specsRoot="$RepoRoot/.forge/specs"

reqDir=$(find "$specsRoot" -type d -name "$normalizedReq-*" 2>/dev/null | head -n 1)

if [ -z "$reqDir" ]; then
    echo -e "\e[31mError: No spec directory found for $normalizedReq under $specsRoot\e[0m" >&2
    exit 1
fi

reqFile="$reqDir/requirement.md"
if [ ! -f "$reqFile" ]; then
    echo -e "\e[31mError: requirement.md not found in $reqDir\e[0m" >&2
    exit 1
fi

reqTitle=$(Get-FrontmatterValue "$reqFile" "title")
if [ -z "$reqTitle" ]; then reqTitle="$normalizedReq"; fi

reqStatus=$(Get-FrontmatterValue "$reqFile" "status")
if [ -z "$reqStatus" ]; then reqStatus="unknown"; fi

acceptanceCriteria=$(Get-SectionContent "$reqFile" "Acceptance Criteria")
if [ -z "$(echo "$acceptanceCriteria" | tr -d ' \n')" ]; then
    acceptanceCriteria="_No acceptance criteria found in requirement.md._"
fi

taskSection=""
if [ -n "$TaskId" ]; then
    normalizedTask=$(Normalize-Id "$TaskId" "TASK")
    taskDir="$reqDir/tasks"
    taskFile=$(find "$taskDir" -type f -name "$normalizedTask-*.md" 2>/dev/null | head -n 1)

    if [ -n "$taskFile" ]; then
        taskTitle=$(Get-FrontmatterValue "$taskFile" "title")
        if [ -z "$taskTitle" ]; then taskTitle="$normalizedTask"; fi
        
        taskStatus=$(Get-FrontmatterValue "$taskFile" "status")
        if [ -z "$taskStatus" ]; then taskStatus="unknown"; fi
        
        taskDeps=$(Get-FrontmatterValue "$taskFile" "dependencies")
        if [ -z "$taskDeps" ]; then taskDeps="none"; fi

        taskDesc=$(Get-SectionContent "$taskFile" "Description")
        if [ -z "$(echo "$taskDesc" | tr -d ' \n')" ]; then taskDesc="_No description._"; fi

        taskAC=$(Get-SectionContent "$taskFile" "Acceptance Criteria")
        if [ -z "$(echo "$taskAC" | tr -d ' \n')" ]; then taskAC="_See requirement-level acceptance criteria above._"; fi

        taskFiles=$(Get-SectionContent "$taskFile" "Files to Create/Modify")
        if [ -z "$(echo "$taskFiles" | tr -d ' \n')" ]; then taskFiles="_Not specified._"; fi

        taskSection=$(cat <<EOF

## Current Task: $normalizedTask

| Field | Value |
|---|---|
| Title | $taskTitle |
| Status | $taskStatus |
| Dependencies | $taskDeps |

### Description
$taskDesc

### Task Acceptance Criteria
$taskAC

### Files to Create/Modify
$taskFiles
EOF
)
    else
        taskSection="\n## Current Task: $normalizedTask\n\n_Task file not found._"
    fi
fi

cd "$RepoRoot" || exit 1
diffStat=$(git diff main...HEAD --stat 2>&1 || true)
branch=$(git branch --show-current 2>&1 || echo "unknown")

if [ -z "$(echo "$diffStat" | tr -d ' \n')" ]; then
    diffStat="_No changes detected vs main._"
fi

timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
taskFmVal=$([ -n "$TaskId" ] && Normalize-Id "$TaskId" "TASK" || echo "none")

snapshot=$(cat <<EOF
---
generated: $timestamp
req: $normalizedReq
task: $taskFmVal
branch: $branch
---

# Active Context Snapshot

> **Focus**: You are implementing **$normalizedReq: $reqTitle**. Only use \`.forge/context/*.md\`, this snapshot, and the current code. Ignore earlier chat history.

## Requirement: $normalizedReq

| Field | Value |
|---|---|
| Title | $reqTitle |
| Status | $reqStatus |

### Acceptance Criteria
$acceptanceCriteria
$taskSection

## Working State

### Branch
\`$branch\`

### Changes vs main
\`\`\`
$diffStat
\`\`\`

---

> This file is auto-generated by \`forge-context.sh\`. Regenerate with:
> \`./scripts/forge-context.sh -ReqId $normalizedReq$([ -n "$TaskId" ] && echo " -TaskId $(Normalize-Id "$TaskId" "TASK")")\`
EOF
)

mkdir -p "$forgeDir"
echo "$snapshot" > "$outputFile"

echo ""
echo -e "  \e[36m[FORGE-CONTEXT] Snapshot generated\e[0m"
echo -e "  \e[97mREQ:    $normalizedReq — $reqTitle\e[0m"
if [ -n "$TaskId" ]; then
    echo -e "  \e[97mTASK:   $(Normalize-Id "$TaskId" 'TASK')\e[0m"
fi
echo -e "  \e[90mBranch: $branch\e[0m"
echo -e "  \e[90mOutput: $outputFile\e[0m"
echo ""
